openapi: 3.1.0
info:
  version: 1.0.0
  title: <Students app>
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: <Students app>
tags:
  # теги, що ви будете використовувати
servers:
  - url: http://localhost:3000
  - url: https://nodejs-hw-mongodb-3lnf.onrender.com
paths:
  /contacts:
    get:
      $ref: '../swagger/paths/contacts/get.yaml'
    post:
      $ref: '../swagger/paths/contacts/post.yaml'
  /contacts/{contactId}:
    get:
      $ref: '../swagger/paths/contacts/{id}/get.yaml'
    patch:
      $ref: '../swagger/paths/contacts/{id}/patch.yaml'
    delete:
      $ref: '../swagger/paths/contacts/{id}/delete.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      components:
  schemas:
    Contact:
      $ref: './schemas/Contact.yaml'
    ContactResponse:
      $ref: './schemas/ContactResponse.yaml'
