openapi: 3.1.0
info:
  version: "1.0.0"
  title: Students App
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: An API for managing students and contacts.
tags:
  - name: Contacts
    description: Operations related to contacts
servers:
  - url: http://localhost:3000
  - url: http://127.0.0.1:8080
  - url: https://nodejs-hw-mongodb-3lnf.onrender.com
paths:
  /contacts:
    get:
      $ref: "../swagger/paths/contacts/get.yaml"
    post:
      $ref: "../swagger/paths/contacts/post.yaml"
  /contacts/{id}:
    get:
      $ref: "../swagger/paths/contacts/{id}/get.yaml"
    patch:
      $ref: "../swagger/paths/contacts/{id}/patch.yaml"
    delete:
      $ref: "../swagger/paths/contacts/{id}/delete.yaml"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    Contact:
      $ref: "../swagger/components/schemas/Contact.yaml"
    ContactResponse:
      $ref: "../swagger/components/schemas/ContactResponse.yaml"
